version: "2"

services:
    open-api:
        image: node:8.10
        volumes:
            - .:/fcc-openapi
        working_dir: /fcc-openapi
        command:
            - node 
            - src/app.js
        ports:
            - "8080:8080"
